export const CoreClassDatabase = [
    {
        Name: "Bard",
        ID: "C1",
        //////Image: require("../../assets/Characters/Bard.png"),
        Level: 1,
        Health: 96,
        CurrentHealth: 96,
        Mana: 100,
        CurrentMana: 100,
        Attack: 5,
        Magic: 7,
        Mind: 7,
        Resistance: 8,
        Defence: 5,
        Luck: 0,
        Speed: 69,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Bezerker",
        ID: "C2",
        //////Image: require("../../assets/Characters/Berzerker.png"),
        Level: 1,
        Health: 145,
        CurrentHealth: 145,
        Mana: 100,
        CurrentMana: 100,
        Attack: 9,
        Magic: 4,
        Mind: 4,
        Resistance: 6,
        Defence: 6,
        Luck: 0,
        Speed: 69,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Black Mage",
        ID: "C3",
        //////Image: require("../../assets/Characters/Black_Mage.png"),
        Level: 1,
        Health: 84,
        CurrentHealth: 84,
        Mana: 100,
        CurrentMana: 100,
        Attack: 5,
        Magic: 7,
        Mind: 6,
        Resistance: 8,
        Defence: 4,
        Luck: 0,
        Speed: 69,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Dark Knight",
        ID: "C4",
        Level: 1,
        //////Image: require("../../assets/Characters/Dark_Knight.png"),
        Health: 112,
        CurrentHealth: 112,
        Mana: 100,
        CurrentMana: 100,
        Attack: 8,
        Magic: 8,
        Mind: 6,
        Resistance: 7,
        Defence: 7,
        Luck: 0,
        Speed: 69,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Devout",
        ID: "C5",
        //////Image: require("../../assets/Characters/Devout.png"),
        Level: 1,
        Health: 111,
        CurrentHealth: 111,
        Mana: 100,
        CurrentMana: 100,
        Attack: 5,
        Magic: 8,
        Mind: 9,
        Resistance: 9,
        Defence: 9,
        Luck: 0,
        Speed: 63,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Dragoon",
        ID: "C6",
        //////Image: require("../../assets/Characters/Dragoon.png"),
        Level: 1,
        Health: 120,
        CurrentHealth: 120,
        Mana: 100,
        CurrentMana: 100,
        Attack: 8,
        Magic: 7,
        Mind: 6,
        Resistance: 5,
        Defence: 7,
        Luck: 0,
        Speed: 83,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Gladiator",
        ID: "C7",
        //////Image: require("../../assets/Characters/Gladiator.png"),
        Level: 1,
        Health: 144,
        CurrentHealth: 144,
        Mana: 100,
        CurrentMana: 100,
        Attack: 8,
        Magic: 6,
        Mind: 6,
        Resistance: 6,
        Defence: 7,
        Luck: 0,
        Speed: 69,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Knight",
        ID: "C8",
        //////Image: require("../../assets/Characters/Knight.png"),
        Level: 1,
        Health: 122,
        CurrentHealth: 122,
        Mana: 100,
        CurrentMana: 100,
        Attack: 6,
        Magic: 6,
        Mind: 6,
        Resistance: 6,
        Defence: 9,
        Luck: 0,
        Speed: 56,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Magus",
        ID: "C9",
        ////Image: require("../../assets/Characters/Magus.png"),
        Level: 1,
        Health: 97,
        CurrentHealth: 97,
        Mana: 100,
        CurrentMana: 100,
        Attack: 5,
        Magic: 9,
        Mind: 6,
        Resistance: 9,
        Defence: 5,
        Luck: 0,
        Speed: 63,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Monk",
        ID: "C10",
        ////Image: require("../../assets/Characters/Monk.png"),
        Level: 1,
        Health: 132,
        CurrentHealth: 132,
        Mana: 100,
        CurrentMana: 100,
        Attack: 8,
        Magic: 5,
        Mind: 6,
        Resistance: 6,
        Defence: 6,
        Luck: 0,
        Speed: 69,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Ninja",
        ID: "C11",
        ////Image: require("../../assets/Characters/Ninja.png"),
        Level: 1,
        Health: 118,
        CurrentHealth: 118,
        Mana: 100,
        CurrentMana: 100,
        Attack: 8,
        Magic: 6,
        Mind: 6,
        Resistance: 6,
        Defence: 6,
        Luck: 0,
        Speed: 69,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Ranger",
        ID: "C12",
        ////Image: require("../../assets/Characters/Ranger.png"),
        Level: 1,
        Health: 108,
        CurrentHealth: 108,
        Mana: 100,
        CurrentMana: 100,
        Attack: 6,
        Magic: 6,
        Mind: 6,
        Resistance: 6,
        Defence: 5,
        Luck: 0,
        Speed: 76,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Red Mage",
        ID: "C13",
        ////Image: require("../../assets/Characters/Red_Mage.png"),
        Level: 1,
        Health: 97,
        CurrentHealth: 97,
        Mana: 100,
        CurrentMana: 100,
        Attack: 5,
        Magic: 8,
        Mind: 8,
        Resistance: 8,
        Defence: 5,
        Luck: 0,
        Speed: 69,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Samurai",
        ID: "C14",
        ////Image: require("../../assets/Characters/Samurai.png"),
        Level: 1,
        Health: 130,
        CurrentHealth: 130,
        Mana: 100,
        CurrentMana: 100,
        Attack: 8,
        Magic: 6,
        Mind: 6,
        Resistance: 7,
        Defence: 7,
        Luck: 0,
        Speed: 69,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Spellblade",
        ID: "C15",
        ////Image: require("../../assets/Characters/Spellblade.png"),
        Level: 1,
        Health: 108,
        CurrentHealth: 108,
        Mana: 100,
        CurrentMana: 100,
        Attack: 8,
        Magic: 8,
        Mind: 6,
        Resistance: 6,
        Defence: 6,
        Luck: 0,
        Speed: 76,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Thief",
        ID: "C16",
        ////Image: require("../../assets/Characters/Thief.png"),
        Level: 1,
        Health: 113,
        CurrentHealth: 113,
        Mana: 100,
        CurrentMana: 100,
        Attack: 7,
        Magic: 6,
        Mind: 7,
        Resistance: 6,
        Defence: 6,
        Luck: 0,
        Speed: 101,
        Accuracy: 20,
        Evasion: 22,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Viking",
        ID: "C17",
        ////Image: require("../../assets/Characters/Viking.png"),
        Level: 1,
        Health: 144,
        CurrentHealth: 144,
        Mana: 100,
        CurrentMana: 100,
        Attack: 9,
        Magic: 5,
        Mind: 6,
        Resistance: 6,
        Defence: 6,
        Luck: 0,
        Speed: 66,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Warrior",
        ID: "C18",
        ////Image: require("../../assets/Characters/Warrior.png"),
        Level: 1,
        Health: 144,
        CurrentHealth: 144,
        Mana: 100,
        CurrentMana: 100,
        Attack: 8,
        Magic: 5,
        Mind: 5,
        Resistance: 5,
        Defence: 8,
        Luck: 0,
        Speed: 69,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "White Mage",
        ID: "C19",
        Level: 1,
        ////Image: require("../../assets/Characters/White_Mage.png"),
        Health: 96,
        CurrentHealth: 96,
        Mana: 100,
        CurrentMana: 100,
        Attack: 5,
        Magic: 6,
        Mind: 8,
        Resistance: 9,
        Defence: 5,
        Luck: 0,
        Speed: 69,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    },
    {
        Name: "Tyro",
        ID: "C20",
        ////Image: require("../../assets/Characters/tyro.png"),
        Level: 1,
        Health: 120,
        CurrentHealth: 120,
        Mana: 100,
        CurrentMana: 100,
        Attack: 8,
        Magic: 7,
        Mind: 7,
        Resistance: 7,
        Defence: 7,
        Luck: 0,
        Speed: 81,
        Accuracy: 20,
        Evasion: 20,
        Items: [],
        Spells: [],
        Experience: 0
    }, 
]