import {Types} from '../ItemTypes/Types';

export const staffDatabase = [
    {
        Name: 'Charry Staff',
        Image: require('../../assets/Items/Staffs/Cherry_Staff.png'),
        ID: "WSTF1",
        Type: Types.Staff,
        Price: 100,
        HealthModifier: 0,
        AttackModifier: 0,
        ResistanceModifier: 0,
        DefenceModifier: 0,
        MagicModifier: 25,
        MindModifier: 0,
        LuckModifier: 0,
        SpeedModifier: 0,
        Rank: 1,
        Level: 1,
        EquippedBy: ''
    },
    {
        Name: "Mage's Staff",
        Image: require("../../assets/Items/Staffs/Mage's_Staff.png"),
        ID: "WSTF2",
        Type: Types.Staff,
        Price: 100,
        HealthModifier: 0,
        AttackModifier: 10,
        ResistanceModifier: 0,
        DefenceModifier: 0,
        MagicModifier: 40,
        MindModifier: 0,
        LuckModifier: 0,
        SpeedModifier: 0,
        Rank: 2,
        Level: 1,
        EquippedBy: ''
    },
    {
        Name: 'Mythril Staff',
        Image: require('../../assets/Items/Staffs/Mythril_Staff.png'),
        ID: "WSTF3",
        Type: Types.Staff,
        Price: 100,
        HealthModifier: 0,
        AttackModifier: 0,
        ResistanceModifier: 0,
        DefenceModifier: 0,
        MagicModifier: 40,
        MindModifier: 0,
        LuckModifier: 0,
        SpeedModifier: 0,
        Rank: 2,
        Level: 1,
        EquippedBy: ''
    },
    {
        Name: 'Oak Staff',
        Image: require('../../assets/Items/Staffs/Oak_Staff.png'),
        ID: "WSTF4",
        Type: Types.Staff,
        Price: 100,
        HealthModifier: 0,
        AttackModifier: 0,
        ResistanceModifier: 0,
        DefenceModifier: 0,
        MagicModifier: 25,
        MindModifier: 0,
        LuckModifier: 0,
        SpeedModifier: 0,
        Rank: 1,
        Level: 1,
        EquippedBy: ''
    },
    {
        Name: 'Power Staff',
        Image: require('../../assets/Items/Staffs/Power_Staff.png'),
        ID: "WSTF5",
        Type: Types.Staff,
        Price: 100,
        HealthModifier: 0,
        AttackModifier: 0,
        ResistanceModifier: 0,
        DefenceModifier: 0,
        MagicModifier: 40,
        MindModifier: 0,
        LuckModifier: 0,
        SpeedModifier: 0,
        Rank: 2,
        Level: 1,
        EquippedBy: ''
    },
]