import {Types} from '../ItemTypes/Types'

export const swordDatabase = [
    {
        Name: 'Broadsword',
        //Image: require('../../assets/Items/Swords/Broadsword.png'),
        ID: "WSRD1",
        Type: Types.Sword,
        Price: 100,
        HealthModifier: 0,
        AttackModifier: 10,
        ResistanceModifier: 0,
        DefenceModifier: 0,
        MagicModifier: 0,
        MindModifier: 0,
        LuckModifier: 0,
        SpeedModifier: 0,
        Rank: 1,
        Level: 1,
        EquippedBy: ''
    },
    {
        Name: 'Galbadian Blade',
        //Image: require('../../assets/Items/Swords/Galbadian_Blade.png'),
        ID: "WSRD2",
        Type: Types.Sword,
        Price: 100,
        HealthModifier: 0,
        AttackModifier: 25,
        ResistanceModifier: 0,
        DefenceModifier: 0,
        MagicModifier: 0,
        MindModifier: 0,
        LuckModifier: 0,
        SpeedModifier: 0,
        Rank: 2,
        Level: 1,
        EquippedBy: ''
    },
    {
        Name: 'Iron Sword',
        //Image: require('../../assets/Items/Swords/Iron_Sword.png'),
        ID: "WSRD3",
        Type: Types.Sword,
        Price: 100,
        HealthModifier: 0,
        AttackModifier: 25,
        ResistanceModifier: 0,
        DefenceModifier: 0,
        MagicModifier: 0,
        MindModifier: 0,
        LuckModifier: 0,
        SpeedModifier: 0,
        Rank: 2,
        Level: 1,
        EquippedBy: ''
    },
    {
        Name: 'Longsword',
        //Image: require('../../assets/Items/Swords/Longsword.png'),
        ID: "WSRD4",
        Type: Types.Sword,
        Price: 100,
        HealthModifier: 0,
        AttackModifier: 10,
        ResistanceModifier: 0,
        DefenceModifier: 0,
        MagicModifier: 0,
        MindModifier: 0,
        LuckModifier: 0,
        SpeedModifier: 0,
        Rank: 1,
        Level: 1,
        EquippedBy: ''
    },
    {
        Name: 'Zwill Blade',
        //Image: require('../../assets/Items/Swords/Zwill_Blade.png'),
        ID: "WSRD5",
        Type: Types.Sword,
        Price: 100,
        HealthModifier: 0,
        AttackModifier: 25,
        ResistanceModifier: 0,
        DefenceModifier: 0,
        MagicModifier: 0,
        MindModifier: 0,
        LuckModifier: 0,
        SpeedModifier: 0,
        Rank: 2,
        Level: 1,
        EquippedBy: ''
    },
]