import { Types } from "../ItemTypes/Types";

export const BracersDataBase = [
  {
    Name: "Bronze Bangle",
    //Image: require("../../assets/Items/Bracers/Bronze_Bangle.png"),
    Type: Types.Bracer,
    ID: "IBRC1",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 1,
    ResistanceModifier: 3,
    DefenceModifier: 2,
    MagicModifier: 1,
    MindModifier: 1,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
  {
    Name: "Iron Bangle",
    //Image: require("../../assets/Items/Bracers/Iron_Bangle.png"),
    Type: Types.Bracer,
    ID: "IBRC2",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 1,
    ResistanceModifier: 3,
    DefenceModifier: 2,
    MagicModifier: 1,
    MindModifier: 1,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
];
