import { Types } from "../ItemTypes/Types";

export const HatsDataBase = [
  {
    Name: "Hairband",
    Image: require("../../assets/Items/Hats/Hairband.png"),
    Type: Types.Hat,
    ID: "IHT1",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 0,
    ResistanceModifier: 5,
    DefenceModifier: 3,
    MagicModifier: 0,
    MindModifier: 1,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
  {
    Name: "Twist Headband",
    Image: require("../../assets/Items/Hats/Twist_Headband.png"),
    Type: Types.Hat,
    ID: "IHT2",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 2,
    ResistanceModifier: 4,
    DefenceModifier: 2,
    MagicModifier: 1,
    MindModifier: 1,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
  {
    Name: "Hairband",
    Image: require("../../assets/Items/Hats/Hairband.png"),
    Type: Types.Hat,
    ID: "IHT3",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 0,
    ResistanceModifier: 5,
    DefenceModifier: 2,
    MagicModifier: 1,
    MindModifier: 1,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
  {
    Name: "Wizard's Hat",
    Image: require("../../assets/Items/Hats/Wizard's_Hat.png"),
    Type: Types.Hat,
    ID: "IHT4",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 0,
    ResistanceModifier: 4,
    DefenceModifier: 2,
    MagicModifier: 5,
    MindModifier: 3,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
  {
    Name: "Leather Cap",
    Image: require("../../assets/Items/Hats/Leather_Cap.png"),
    Type: Types.Hat,
    ID: "IHT4",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 0,
    ResistanceModifier: 4,
    DefenceModifier: 2,
    MagicModifier: 1,
    MindModifier: 1,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
];
