import { Types } from "../ItemTypes/Types";

export const HelmsDataBase = [
  {
    Name: "Bronze Helm",
    Image: require("../../assets/Items/Helms/Bronze_Helm.png"),
    Type: Types.Helm,
    ID: "IHLM1",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 1,
    ResistanceModifier: 4,
    DefenceModifier: 4,
    MagicModifier: 0,
    MindModifier: 0,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
  {
    Name: "Warden's Helm",
    Image: require("../../assets/Items/Helms/Warden's_Helm.png"),
    Type: Types.Bracer,
    ID: "IHLM2",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 1,
    ResistanceModifier: 3,
    DefenceModifier: 3,
    MagicModifier: 0,
    MindModifier: 1,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
];
