import { Types } from "../ItemTypes/Types";

export const LightArmorsDataBase = [
  {
    Name: "Copper Cuirass",
    //Image: require("../../assets/Items/Light_Armors/Copper_Cuirass.png"),
    Type: Types.LightArmor,
    ID: "ILTA1",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 0,
    ResistanceModifier: 3,
    DefenceModifier: 4,
    MagicModifier: 0,
    MindModifier: 0,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
  {
    Name: "Leather Clothing",
    //Image: require("../../assets/Items/Light_Armors/Leather_Clothing.png"),
    Type: Types.LightArmor,
    ID: "ILTA2",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 0,
    ResistanceModifier: 3,
    DefenceModifier: 4,
    MagicModifier: 0,
    MindModifier: 0,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
  {
    Name: "Prison Garb",
    //Image: require("../../assets/Items/Light_Armors/Prison_Garb.png"),
    Type: Types.LightArmor,
    ID: "ILTA3",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 0,
    ResistanceModifier: 4,
    DefenceModifier: 4,
    MagicModifier: 0,
    MindModifier: 0,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
  {
    Name: "Vest",
    //Image: require("../../assets/Items/Light_Armors/Vest.png"),
    Type: Types.LightArmor,
    ID: "ILTA4",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 0,
    ResistanceModifier: 4,
    DefenceModifier: 3,
    MagicModifier: 0,
    MindModifier: 0,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
];
