import { Types } from "../ItemTypes/Types";

export const RobesDataBase = [
  {
    Name: "Mage Robe",
    //Image: require("../../assets/Items/Robes/Mage_Robe.png"),
    Type: Types.Robe,
    ID: "IRB1",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 0,
    ResistanceModifier: 6,
    DefenceModifier: 2,
    MagicModifier: 0,
    MindModifier: 0,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
  {
    Name: "Silk Robe",
    //Image: require("../../assets/Items/Robes/Silk_Robe.png"),
    Rarity: 1,
    Type: Types.Bracer,
    Attack: 0,
    Magic: 0,
    Defense: 3,
    Resistance: 5,
    Mind: 0,
    ID: "IRB2",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 0,
    ResistanceModifier: 5,
    DefenceModifier: 3,
    MagicModifier: 0,
    MindModifier: 0,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
  {
    Name: "Cotton Robe",
    //Image: require("../../assets/Items/Robes/Cotton_Robe.png"),
    Type: Types.Bracer,
    ID: "IRB3",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 0,
    ResistanceModifier: 5,
    DefenceModifier: 3,
    MagicModifier: 0,
    MindModifier: 0,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
];
