import { Types } from "../ItemTypes/Types";

export const ShieldDataBase = [
  {
    Name: "Round Shield",
    //Image: require("../../assets/Items/Shields/Round_Shield.png"),
    Type: Types.Shield,
    ID: "ISHLD1",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 0,
    ResistanceModifier: 3,
    DefenceModifier: 4,
    MagicModifier: 0,
    MindModifier: 0,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
  {
    Name: "Bronze Shield",
    //Image: require("../../assets/Items/Shields/Bronze_Shield.png"),
    Type: Types.Shield,
    ID: "ISHLD2",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 0,
    ResistanceModifier: 2,
    DefenceModifier: 4,
    MagicModifier: 0,
    MindModifier: 0,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
  {
    Name: "Buckler",
   //Image: require("../../assets/Items/Shields/Buckler.png"),
    Type: Types.Shield,
    ID: "ISHLD3",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 0,
    ResistanceModifier: 2,
    DefenceModifier: 4,
    MagicModifier: 1,
    MindModifier: 1,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  },
  {
    Name: "Leather Shield",
    //Image: require("../../assets/Items/Shields/Leather_Shield.png"),
    Rarity: 1,
    Type: Types.Shield,
    Attack: 0,
    Magic: 0,
    Defense: 4,
    Resistance: 2,
    Mind: 0,
    ID: "ISHLD4",
    Price: 100,
    HealthModifier: 0,
    AttackModifier: 0,
    ResistanceModifier: 2,
    DefenceModifier: 4,
    MagicModifier: 0,
    MindModifier: 0,
    LuckModifier: 0,
    SpeedModifier: 0,
    Rank: 1,
    Level: 1,
    EquippedBy: "",
  }
];
